defaults: &defaults
  adapter: postgresql
  encoding: unicode
  host: "localhost"
  pool: 5
  username: postgres
  password: "123456"
  sslmode: disable

development:
  <<: *defaults
  database: obituario_development

test:
  <<: *defaults
  database: obituario_test
