default: &default
  adapter: postgresql
  encoding: unicode
  host: "localhost"
  pool: 5
  username: postgres
  password: "123456"
  sslmode: disable

development:
  <<: *default
  database: obituario_development

test:
  <<: *default
  database: obituario_test

production:
  <<: *default
  database: obituario_production
